#!/bin/bash
#initialized ssh-agent and adds private key to it, or creates a private key for a user with the given email (must not exist private and public keys to gen)
if [ $# -ge 2 ]
then
   echo "Usage: (email)"
   exit 1
fi


git config --global push.default current

#configure email if specified
if [ $# -ge 1 ]
then
   git config --global user.email "$1"
   email=$1
fi

#check to see if ssh-agent is already running
if [[ $(ps ax | grep [s]sh-agent | wc -l) -le 0 ]] ; then
   eval "$(ssh-agent -s)" #start-up a background ssh agent
fi


if [[ -f ~/.ssh/id_ed25519.pub ]] && [[ -f ~/.ssh/id_ed25519 ]];
then
   echo "Hello user with email:"
   email=$(cat ~/.ssh/id_ed25519.pub | grep -o " [a-zA-Z.@]*" | tail -n1)
   echo $email
   echo "**** Assumed from previously generated public key"
else
   if [[ $# -eq 0 ]]
   then 
      echo "enter email:"
      read email
      git config --global user.email $email
      ssh-keygen -t ed25519 -C "$email"
   else
      ssh-keygen -t ed25519 -C "$email" #passphrase here entered again at ssh-add
   fi
   echo "Add the following as the content of a new key configured at https://github.com/settings/ssh:"
   cat ~/.ssh/id_ed25519.pub
   echo "type anything once you've added the key to your github account..."
   read anything
fi

#After this, id_ed25519 and id_ed25519.pub are created
if [[ $(echo $(ssh-add -l) | grep -oF $email | wc -l) -gt 0 ]]; then
   ssh-add ~/.ssh/id_ed25519 #adds the private key to the ssh-agent
fi
